apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rvxb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rvxb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rvxb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rvxb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rvxb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ctue-tenant/rhtap-demo-app/hacbs-test-project-rvxb@sha256:bf9dc421532da7d07e77eeac136c2c7bd9eca3037741238bb1939d8b1c45bcd3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
